FROM node:14

WORKDIR /usr/src/app

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install

COPY . .

ENTRYPOINT [ "/usr/src/app/entrypoint.d.sh" ]

EXPOSE 8080

CMD [ "npm", "run","start:dev" ]